version: '3.7'

x-service-base: &service-base
  init: true
  restart: unless-stopped
  environment:
    TZ: "Europe/Paris"

x-volume-base: &volume-base
  driver: local

services:
  db:
    <<: *service-base
    image: postgres:latest
    container_name: db
    env_file:
      - backend/.env
    networks:
      - endence

  backend:
    <<: *service-base
    depends_on:
      - db
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file:
      - backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - endence
  
  frontend:
    <<: *service-base
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:3000
    depends_on:
      - backend
    networks:
      - endence

  # adminer:
  #   <<: *service-base
  #   image: adminer
  #   container_name: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - endence

networks:
  endence:
    driver: bridge
