FROM node:16.20.2
WORKDIR /usr/src/app
COPY package*.json ./
#RUN npm install : une fois installé une fois, remettre en commentaire
RUN npm install 
COPY . .
COPY entry.sh entry.sh
RUN chmod +x entry.sh
EXPOSE 3000
CMD [ "sh", "entry.sh"]